- src/htdocs/js/fdsn/UrlBuilderFormatter.js
This was requested by Paul Earle.
> Update US catalog and contributor mapping with PDE designation.

- gruntconfig/config.js
- gruntconfig/connect.js
- gruntconfig/watch.js
- src/lib/classes/detail/cap.inc.php
- src/lib/classes/detail/geojson.inc.php
- src/lib/classes/detail/geojsonp.inc.php
- src/lib/classes/detail/kml.inc.php
- src/lib/classes/detail/kmlraw.inc.php
- src/lib/classes/detail/quakeml.inc.php
- src/lib/classes/fdsn/FDSNEventWebService.class.php
- src/lib/classes/fdsn/FDSNIndex.class.php
- src/lib/classes/pdl/ProductIndex.class.php
Note: This assumes #67 is merged. I can rebase as needed.
> LATESTEQ-293

- src/htdocs/glossary.php
- src/lib/classes/detail/geojson.inc.php
- src/lib/classes/detail/geojsonp.inc.php
- src/lib/classes/fdsn/FDSNEventWebService.class.php
- src/lib/classes/fdsn/FDSNIndex.class.php
- src/lib/classes/fdsn/GeoJSONFeed.class.php
- src/lib/classes/pdl/Event.class.php
Output deleted events when requesting includeSuperseded.
> Improve deleted superseded

- src/htdocs/js/fdsn/UrlBuilderFormatter.js
> Add Induced Seismicity Project

- src/htdocs/csv.php
- src/htdocs/glossary.php
- src/lib/classes/fdsn/CSVFeed.class.php
Partially fixes #103 .  Documentation pages needs to be updated to list all fields, and make sure they are properly described.
> add additional origin product properties to csv format

- src/lib/classes/fdsn/AtomFeed.class.php
> Added Contributor and Author to Atom feed

- src/lib/classes/fdsn/FDSNEventWebService.class.php
> Add minradius and minradiuskm into FDSN web service

- src/htdocs/js/fdsn/FDSNSearchForm.js
- src/lib/application.wadl
- src/lib/classes/fdsn/FDSNEventWebService.class.php
- src/lib/classes/fdsn/FDSNIndex.class.php
- src/lib/classes/fdsn/FDSNQuery.class.php
fixes usgs/earthquake-event-ws#132
- Removed basictime and basicmagnitude query parameters
> Usgs/earthquake event ws#132

- src/htdocs/js/fdsn/LocationView.js
- src/htdocs/search.php
fixes usgs/earthquake-event-ws#123
- Added disclaimer and jump link to disclaimer
> Usgs/earthquake event ws#123

- src/htdocs/js/fdsn/DateTimeView.js
- src/htdocs/js/fdsn/MagnitudeView.js
> Select radio buttons when search parameters exist

- src/conf/config.inc.php
- src/lib/configure.php
> Add scenario_mode configuration option

- gruntconfig/connect.js
- src/htdocs/detail.php
- src/lib/classes/detail/quakeml.inc.php
- src/lib/classes/fdsn/FDSNEventWebService.class.php
> Output phase-data quakeml for quakeml detail

- src/htdocs/js/fdsn/FDSNModel.js
- src/htdocs/js/fdsn/FDSNSearchForm.js
fixes usgs/earthquake-event-ws#121
> Usgs/earthquake event ws#121

- src/htdocs/search.php
fixes #136 
Update search page title on scenario mode. Make it obvious that the user is in scenario mode
> Brand Search Page with Scenario

- src/lib/sql/fdsnws/getEventSummary.sql
> Add scenario types to getEventSummary stored procedure

- src/htdocs/js/fdsn/SelectField.js
-fixes usgs/earthquake-event-ws#155
> Usgs/earthquake event ws#155

- src/htdocs/js/fdsn/DateTimeView.js
> Update times to always use a two digit month and day

- src/htdocs/js/fdsn/SelectField.js
this breaks the association between the label and the input
> Fix bug where id does not match label

- src/htdocs/search.php
fixes usgs/earthquake-event-ws#172
- Updated broken link
> updated link to anss comprehensive earthquake catalog

- src/htdocs/search.php
fixes usgs/earthquake-event-ws#177
- Updated link
> updated significant earthquake archive link

- src/lib/sql/fdsnws/summary_sql.php
Make fdsn *Summary tables use innodb engine.
> Update summary tables to be created with innodb engine

- src/htdocs/summary.php
> Update magnitude to include values that will be rounded to listed threshold

- src/htdocs/_navigation.inc.php
> Update section navigation

- src/htdocs/search.php
fixes usgs/earthquake-event-ws#174
> Changed title of search page

- src/htdocs/index.php
fixes #180 
All links had already been updated, this just makes the links more consistent.
> Update references to policy.php

- src/htdocs/_eq_navigation.inc.php
- src/htdocs/search.php
> Update _navigation.inc.php for search.php

- src/lib/classes/fdsn/GeoJSONFeed.class.php
fixes #157 
Does this look good?
> Default to "earthquake" on summary feed event type

- LICENSE.md
- README.md
- src/htdocs/atom.php
- src/htdocs/kml.php
- src/htdocs/summary.php
- src/lib/classes/detail/kml.inc.php
- src/lib/classes/detail/kmlraw.inc.php
- src/lib/classes/fdsn/AtomFeed.class.php
> switched from http to https

- package.json
- src/htdocs/detail.php
- src/htdocs/fdsn.php
- src/lib/classes/fdsn/AtomFeed.class.php
- src/lib/classes/fdsn/CSVFeed.class.php
- src/lib/classes/fdsn/FDSNIndex.class.php
- src/lib/classes/fdsn/GeoJSONFeed.class.php
- src/lib/classes/fdsn/KMLFeed.class.php
- src/lib/classes/fdsn/QuakemlFeed.class.php
- src/lib/classes/fdsn/TextFeed.class.php
Fixes #153 
Fixes #205 
Fixes #224
> Utf8 encoding

- src/htdocs/js/fdsn/FDSNSearchForm.js
> Only expand "Advanced Search" when there are advanced search params

- src/htdocs/search.php
> added link

- src/htdocs/_navigation.inc.php
> removed duplicates from left nav and cleaned up code

- src/htdocs/fdsn.php
> fixed typo

- src/lib/classes/detail/kml.inc.php
- src/lib/classes/detail/kmlraw.inc.php
> Add content disposition header to kml files

- src/lib/classes/detail/kmlraw.inc.php
> If countours exist and are visible, show the legend

- src/htdocs/_navigation.inc.php
- src/htdocs/index.php
> Updated ENS links

- src/htdocs/js/fdsn/FDSNModel.js
- src/htdocs/js/fdsn/FDSNSearchForm.js
- src/htdocs/js/fdsn/UrlManager.js
> Preserve Settings from Earthquake Map/List

- src/htdocs/inc/search-advanced.inc.html
> added link to product type section

- src/htdocs/js/fdsn/FDSNSearchForm.js
It will use the search parameters if they are set
> Update mapposition to default to worldwide extents

- src/htdocs/js/fdsn/FDSNSearchForm.js
If you honor the map/list viewModes, then you will only ever see the settings panel when switching between the two on mobile.
> Do not honor map/list view modes settings

- src/lib/classes/pdl/ProductStorage.class.php
> Handle content millisecond timestamps more carefully

- src/lib/classes/fdsn/FDSNEventWebService.class.php
> Change how event redirects work

- src/htdocs/fdsn.php
- src/lib/classes/fdsn/FDSNEventWebService.class.php
@emartinez-usgs , @llastowka-usgs 
see also https://github.com/usgs/hazdev-basemap/pull/12
> Add validation for jsonp callback parameter

- src/lib/sql/fdsnws/productSummaryEventStatus.sql
preferredProduct only includes preferred origins from the preferred source.
> Switch source for products so non-preferred catalogs are included

- package.json
- src/lib/sql/fdsnws/_config.inc.php
- src/lib/sql/fdsnws/populateProductSummaryEventStatus.sql
Was incrementally deployed to larger systems, this deploys for smaller in ~10s.
> Add script to populate productSummaryEventStatus table.

- src/lib/sql/feplus/feplus.sql
- src/lib/sql/feplus/get_feregion.sql
- src/lib/sql/feplus/get_region_name.sql
- src/lib/sql/feplus/point_in_one_polygon.sql
> Resolves: Update FE+ Schema

- src/lib/classes/pdl/ProductIndex.class.php
- src/lib/sql/fdsnws/recreateEventSummary.sql
Adds UTF-8 encoding to `region` on table creation and access. Yet untested; must be done on `hazdev-realtime` development stack.
> Hazdev realtime issue 27

- src/lib/sql/fdsnws/getEventSummary.sql
- src/lib/sql/fdsnws/getProductProperty.sql
- src/lib/sql/fdsnws/updateEventSummary.sql
once merged, run new realtime stack and observe whether utf8 propogates.
> used utf8 on stored procedures

- src/lib/classes/fdsn/FDSNEventWebService.class.php
> Closes #308 : Unexpected 409 response

- src/conf/config.inc.php
- src/htdocs/inc/search-basic.inc.php
- src/htdocs/search.php
- src/htdocs/summary.php
- src/lib/classes/detail/kml.inc.php
- src/lib/classes/detail/kmlraw.inc.php
- src/lib/classes/fdsn/KMLFeed.class.php
Closes #309
Closes #291
Closes #290
Closes #274
> Minor Fixes - CHS Issue 30

- code.json
- package.json
> Increment version number
